### ISSUE TITLE
L10n Entry of compost is missing

### ISSUE THREAD

**Issue by Limone81** [sashaman/HorseExtension#13]
The l10n entries are missing for compost. You have to implement someones to moddesc or separated l10n-file of the map, so you get the right text via Esc-Menu at the prices tab. Greets

adds like following in the l10n-section of moddesc:
<text name="fillType_compost">
            <en>Compost</en>
            <de>Kompost</de>
		</text>

**Comment by Limone81** [comment]
Only if you have already a HE-Ready map. If you do the complete DIY for HE, the entries are in the l10n_xx.xml included.

**Comment by sashaman** [comment]
https://github.com/sashaman/HorseExtension/commit/eec0fba61965f7f509f52c47a6c17cf93c3b7aba#commitcomment-55984385 

close if u feel thats ok 😃

**Comment by Limone81** [comment]
ok
